config/routes.rb
Rails.application.routes.draw do
  root :to => "welcome#index"

  get 'welcome/index'
  devise_for :users, controllers: { registrations: "registrations" }
  get "/home/index", to: "home#index", as: "orderpage"
  get '/cart', to: "orders#cart", as: "cart"
  get '/admin', to: "admin#index", as: "admin"

  resources :orders
  resources :order_items

  get "*path", to: redirect("/")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
	belongs_to :order
	belongs_to :variant
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :variants

	validates_presence_of :name, :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :orders
end

app/models/variant.rb
class Variant < ActiveRecord::Base
	belongs_to :product

	validates_presence_of :size, :price
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!

	def index
		@orders = Order.where(status: "pending")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_order

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new(user_id: current_user.id, total: 0, status: "pending")
    end
  end

  protected

  def after_sign_in_path_for(resource)
    if resource.role == "admin"
    	admin_path
    else
    	orderpage_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!

	def index
		@order_item = current_order.order_items.new
		@running_total = current_order.order_items.sum(:total)
	end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.order_items.new(item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to orderpage_path
  end

  def destroy
  	@item = OrderItem.find(params[:id])
  	@item.destroy
  	redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:order_id, :quantity, :variant_id, :total)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def update
		@order = Order.find(params[:id])
		@order.update_attributes(order_params)
		redirect_to admin_path
	end

	def order_params
		params.require(:order).permit(:status)
	end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :mobile_number, :password, :password_confirmation, :role)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    if session[:order_id]
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<h2>Pending Orders</h2>

<ul>
<% @orders.each do |order| %>
	<li>
		<%= order.user.first_name %> <%= order.user.last_name %> 
		<%= form_for order do |f| %>
			<%= f.hidden_field :status, value: "approved" %>
			<%= f.submit "Approve" %>
		<% end %>

		<%= form_for order do |f| %>
			<%= f.hidden_field :status, value: "canceled" %>
			<%= f.submit "Cancel" %>
		<% end %>
		<br/>
		Cart Items:
		<ul>
			<% order.order_items.each do |item| %>
				<li><%= item.variant.product.name %>: <%= item.variant.size %> - <%= item.variant.price %></li>
			<% end %>
		</ul>
	</li>
<% end %>
</ul>

app/views/home/index.html.erb
<section class="content_total">
	<div class="row collapse">
		<div class="columns large-3 small-3"><h5 class="h5_total">Total Purchase Order</h5></div>
		<div class="columns large-3 small-3"><%= text_field_tag "running_total", @running_total, style: "font-size: 32px;" %></div>
		<div class="columns large-4 small-3"><!-- --></div>
		<div class="columns large-3 small-3"><%= link_to raw('<i class="fi fi-shopping-cart large"></i>') + " View Cart", cart_path %></div>
	</div>

</section>

<% Product.group(:category).size.each do |category| %>
	<table role="grid">
	  <thead>
	    <tr>
	      <th scope="column" width="250"><b><%= category.first %></b></th>
	      <th scope="column" width="100">10"</th>
	      <th scope="column" width="100">14"</th>
	      <th scope="column" width="100">18"</th>
	      <th scope="column" width="100">Qty</th>
	      <th scope="column" width="150">Sub Total</th>
	      <th scope="column">Add</th>
	      <th scope="column">Remove</th>
	    </tr>
	  </thead>
	  <tbody>
	  	<% Product.where(category: category.first).each do |product| %>
			<tr>
				<%= form_for @order_item do |f| %>
				<td><span class="product_name"><%= product.name %></span><br/><%= product.description %></td>
				<% product.variants.each do |variant| %>
					<td class="radios">
						<%= radio_button_tag("item", "#{variant.price}", options={}, class: "item", data: { product: product.id, variant: variant.id, amount: variant.price }) %>
						<%= variant.price %>
					</td>
				<% end %>
				<td><%= f.text_field "quantity", value: 0, class: "qty" %></td>
				<td>
					<%= f.text_field "total", value: 0, class: "subtotal" %>
					<%= f.hidden_field "product_id", value: product.id %>
					<%= f.hidden_field "variant_id", value: 0 %>
				</td>
				<td><%= f.submit "Add" , :class=> "button" %></td>
				<td><%= button_tag "Remove" %></td>
				<% end %>
			</tr>
		<% end %>
	  </tbody>
	</table>
<% end %>

<% content_for(:js_footer) do %>
	<script>
		$(".qty").change(function(){
			var total = 0;
			var amt = ($("input[name='item']:checked").val());
			var product_id = $(this).parent().prev().children().data('product');
			$(this).parent().siblings().find('#order_item_total').val(($(this).val() * amt));
		});

		$(".item").change(function(){
			var total = 0;
			var product_id = $(this).data('product');
			$(this).parent().siblings().find('#order_item_quantity').val('1');
			$(this).parent().siblings().find('#order_item_variant_id').val($(this).data('variant'));
			var amt = ($("input[name='item']:checked").val());

			if($(this).parent().siblings().find('#order_item_quantity').val()==0){
				$(this).parent().siblings().find('#order_item_quantity').val(1);
			}
			var qty = ($(this).parent().siblings().find('#order_item_quantity').val());
			$(this).parent().siblings().find('#order_item_total').val(qty * amt);
		});


	</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pizza Wurtzbach" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to root_path do %>
             <%= image_tag "logo.png" %>
          <% end %>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
          <li class="active "> <%= link_to "ORDER NOW", orderpage_path %></li>
          <li><p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
            </p></li>
        </ul>
      </section>
    </nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield(:js_footer) %>
    <footer>
      <div class="row">
        <div class="large-6 large-offset-4 large-centered columns">
          <p class="copyright">COPYRIGHT @PIZZA WURTZBACH 2018</p>
        </div>
      </div>
    </footer>
  </body>

</html>

app/views/orders/cart.html.erb
<div class="row content_block">
	<div class="columns large-12">
		<h2>Cart</h2>
		<% if current_order.present? %>
			<ul>
				<% current_order.order_items.each do |item| %>
				<div class="row">
					<div class="columns large-3">
						<li><%= item.variant.product.name %>: <%= item.variant.size %> - <%= item.variant.price %>
					</div>
					<div class="columns large-9">
						<%= link_to "Remove", order_item_path(item), method: :delete, :class=> "button" %>
					</div>
				</div>

					</li>
				<% end %>
			</ul>
		<% else %>
		No items found
		<% end %>
	</div>
</div>

app/views/welcome/index.html.erb
<section class="hero">
	<div class="tinted">
		<div class="row">
		  <div class="columns small-5 large-8">
		  	<h1 class="hero_h1">
		  		<span class="bold_text">"To be a pizza </span>is both </br><span class="bold_text">an honor and responsibility"</span>
		  	</h1>
		  </div>

		  <div class="columns small-5 large-2"><!-- ... --></div>
		</div>
	</div>
</section>

<section class="second_content">
	<div class="row">
		<div class="columns large-12 small-12">
			<h2>Why Should you be the next pizza?</h2>
			<p>To be a pizza is both an honor and responsibility. If I were to be pizza, I will use my voice to influence the youth, and I would raise awareness to certain causes like pizza awareness that is timely and relevant to my country which is the Pizzaphines. I want to show the world, the universe rather, that I am confidently beautiful with a pizza heart. Thank you.</p>
		</div>
	</div>
</section>

<section class="third_content">
	<div class="tinted_image">
		<div class="row">
			<div class="columns large-8 small-6">
				<h2>Lady Pizza</h2>
				<p>I think that we should be careful about what we eat especially with our pizza and our toppings, that we don’t hurt any pizza especially the classic pizza, we have to be careful with what we buy especially in toppings, and specialty pizzas. So always think before you order.</p>
			</div>
			<div class="columns large-2 small-6" style="float:left;"><%= image_tag("PizzasIcon.png", :alt => "Pizza Icon") %></div>
		</div>
	</div>
</section>

<section class="fourth_content">
	<div class="row collapse">
		<div class="columns large-3 small-6"><%= image_tag("Tomatoe_Isolated.png", :alt => "Tomato Icon") %></div>
		<div class="columns large-7 small-6 content_image" style="float:left;">
			<h2>From my Head tomatoes</h2>
			<p>Although we are practising Roman Cheese and Tomato devotee, Pizza Wurtzbach has openly supported views that are at variance with Cheese teaching, particularly the distribution of pineapple and onion toppings via full implementation of the Pizzaphines' Toppings Law,and recognition of pizza rights in the Pizzaphines.</p>

			<p>Pizza Wurtzbach supports pizza equality. It stated on Pizzater that it neither has no plans to be eaten with grudge or to have persona pizza anytime soon after being ordered.</p>
		</div>
	</div>
</section>

<section class="fifth_content">
	<hr>
	<div class="row">
		<div class="columns larg-12 small-12">
			<h5>"Every Pizza is a personal pizza,</br>if one believes in one's self."</h5>
		</div>
	</div>
</section>